/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353439",
        "primary-container": "#7c3aed",
        "surface-container": "#1f1f23",
        "surface-container-low": "#1b1b1f",
        "outline": "#958da1",
        "on-secondary-fixed": "#181445",
        "surface-container-lowest": "#0e0e12",
        "on-background": "#e5e1e7",
        "primary-fixed": "#eaddff",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary-fixed": "#25005a",
        "secondary-fixed": "#e3dfff",
        "surface-dim": "#131317",
        "inverse-primary": "#732ee4",
        "outline-variant": "#4a4455",
        "primary-fixed-dim": "#d2bbff",
        "inverse-on-surface": "#303034",
        "secondary-fixed-dim": "#c4c1fb",
        "on-tertiary-fixed-variant": "#6900b3",
        "tertiary-container": "#8d36db",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#2c0051",
        "on-secondary-container": "#b3afe9",
        "secondary": "#c4c1fb",
        "on-surface-variant": "#ccc3d8",
        "on-secondary": "#2d2a5b",
        "on-tertiary-container": "#f2dfff",
        "surface-container-high": "#2a292e",
        "on-tertiary": "#490080",
        "on-primary": "#3f008e",
        "tertiary": "#ddb7ff",
        "on-error": "#690005",
        "inverse-surface": "#e5e1e7",
        "on-secondary-fixed-variant": "#444173",
        "on-surface": "#e5e1e7",
        "surface-tint": "#d2bbff",
        "surface-container-highest": "#353439",
        "tertiary-fixed": "#f0dbff",
        "error": "#ffb4ab",
        "surface": "#131317",
        "surface-bright": "#39393d",
        "primary": "#d2bbff",
        "on-error-container": "#ffdad6",
        "secondary-container": "#444173",
        "on-primary-container": "#ede0ff",
        "tertiary-fixed-dim": "#ddb7ff",
        "background": "#131317",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
